version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7
    container_name: fastspot-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: Admin123!
      MONGO_INITDB_DATABASE: fastspot
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - fastspot-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5

  # MongoDB Express (Web UI для БД)
  mongo-express:
    image: mongo-express:latest
    container_name: fastspot-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: Admin123!
      ME_CONFIG_MONGODB_URL: mongodb://admin:Admin123!@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - fastspot-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  fastspot-network:
    driver: bridge

